### ISSUE TITLE
QueueUrl should always be available

### ISSUE THREAD

**Issue by komuw** [komuw/wijisqs#20]
we have this bug:
```bash
Invalid type for parameter QueueUrl, value: None, type: <class 'NoneType'>, valid types: <class 'str'>
workers_1        | {'QueueUrl': 'https://eu-west-1.queue.amazonaws.com/112056393267/NetworkIOTaskQueue', 'ResponseMetadata': {'RequestId': '75d48824-21d5-535e-a86f-dd2f2f0a3407', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': '75d48824-21d5-535e-a86f-dd2f2f0a3407', 'date': 'Tue, 19 Mar 2019 15:37:03 GMT', 'content-type': 'text/xml', 'content-length': '340'}, 'RetryAttempts': 0}, 'event': 'wijisqs.SqsBroker._create_queue', 'queue_name': 'NetworkIOTaskQueue'}
workers_1        | {'event': 'wiji.Task.delay', 'stage': 'end', 'state': 'check broker failed', 'error': '', 'task_name': 'NetworkIOTask', 'queue_name': 'NetworkIOTaskQueue', 'worker_id': '94N4MXQZ5SIPW2SP3', 'process_id': 1}
workers_1        | Traceback (most recent call last):
workers_1        |   File "/usr/local/lib/python3.7/site-packages/wiji/task.py", line 378, in _broker_check
workers_1        |     await self.the_broker.check(queue_name=self.queue_name)
workers_1        |   File "/usr/local/lib/python3.7/site-packages/wijisqs/broker.py", line 322, in check
workers_1        |     executor, functools.partial(self._tag_queue, queue_name=queue_name)
workers_1        |   File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
workers_1        |     result = self.fn(*self.args, **self.kwargs)
workers_1        |   File "/usr/local/lib/python3.7/site-packages/wijisqs/utils.py", line 24, in wrapper
workers_1        |     return func(*args, **kwargs)
workers_1        |   File "/usr/local/lib/python3.7/site-packages/wijisqs/broker.py", line 348, in _tag_queue
workers_1        |     response = self.client.tag_queue(QueueUrl=self.QueueUrl, Tags=self.queue_tags)
workers_1        |   File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 357, in _api_call
workers_1        |     return self._make_api_call(operation_name, kwargs)
workers_1        |   File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 634, in _make_api_call
workers_1        |     api_params, operation_model, context=request_context)
workers_1        |   File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 682, in _convert_to_request_dict
workers_1        |     api_params, operation_model)
workers_1        |   File "/usr/local/lib/python3.7/site-packages/botocore/validate.py", line 297, in serialize_to_request
workers_1        |     raise ParamValidationError(report=report.generate_report())
workers_1        | botocore.exceptions.ParamValidationError: Parameter validation failed:
workers_1        | Invalid type for parameter QueueUrl, value: None, type: <class 'NoneType'>, valid types: <class 'str'>
workers_1        |
workers_1        | The above exception was the direct cause of the following exception:
workers_1        |
workers_1        | Traceback (most recent call last):
workers_1        |   File "/usr/local/lib/python3.7/asyncio/runners.py", line 43, in run
workers_1        |     return loop.run_until_complete(main)
workers_1        |   File "/usr/local/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
workers_1        |     return future.result()
workers_1        |   File "/usr/local/lib/python3.7/site-packages/cli/cli.py", line 126, in async_main
workers_1        |     await gather_tasks
workers_1        |   File "/usr/local/lib/python3.7/site-packages/wiji/worker.py", line 247, in consume_tasks
workers_1        |     await self.the_task._broker_check(from_worker=True)
workers_1        |   File "/usr/local/lib/python3.7/site-packages/wiji/task.py", line 394, in _broker_check
workers_1        |     ) from e
workers_1        | ValueError: The broker for task: `DiskIOTask` failed check request.
```

**Comment by komuw** [comment]
I think it was introduced by: https://github.com/komuw/wijisqs/pull/19

We should check if SQS has an api to get QueueUrl and call that for all `check` calls
